name: "build"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "install cargo"
        run: sudo apt-get install -y cargo
      - name: "get mdbook"
        run: "cargo install mdbook"
      - name: "build"
        run: "make ci"
