name: "build"

on:
  - push
  - pull_request
  - schedule:
      - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v2
      - name: "setup repo"
        run: "echo '@testing https://dl-cdn.alpinelinux.org/alpine/edge/testing' >> /etc/apk/repositories"
      - name: "update repo"
        run: "apk update"
      - name: "setup deps"
        run: "apk add make bash git mdbook@testing"
      - name: "build"
        run: "make ci"
      - uses: actions/upload-artifact@v3
        with:
          name: notebook
          path: book/
